apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kg-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/kg_exporter/helm-charts/
    chart: kg-exporter
    targetRevision: 0.*.*
    helm:
      valuesObject:
        settings:
          metadata_service_url: "http://metadata-service/api/v0/graph"
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
