apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policy-manager
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gatekeeper-policy-manager
    repoURL: https://sighupio.github.io/gatekeeper-policy-manager
    targetRevision: 0.10.0
    helm:
      valuesObject:
        service:
          type: NodePort
        config:
          secretKey: supersecuresecretkey 
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            #kubernetes.io/ingress.class: "nginx"
            #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            #nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=https://$host$request_uri$is_args$args
            #nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
            #nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
            #nginx.ingress.kubernetes.io/secure-backends: "true"
            #nginx.ingress.kubernetes.io/configuration-snippet: |
            # auth_request_set $token $upstream_http_authorization;
            # proxy_set_header Authorization $token;
            #forecastle.stakater.com/expose: "true"
            #forecastle.stakater.com/appName: "Gatekeeper Policy Manager"
            #forecastle.stakater.com/icon: "https://raw.githubusercontent.com/sighupio/gatekeeper-policy-manager/master/app/static-content/logo.svg"
          path: /
          pathType: Prefix
          hosts:
            - gpm.integration

          hosts:
            - host: gpm.integration
              paths: ["/"]
              pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
