apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metadata-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: knowledge-graph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/glaciation-metadata-service/helm-charts/
    chart: glaciation-metadata-service
    targetRevision: 0.*.*
    helm:
      valuesObject:
        glaciation-metadata-service:
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            hosts:
              - metadata-service.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
