apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://hiro-microdatacenters-bv.github.io/monitoring-stack/helm-charts/
    chart: monitoring-stack
    targetRevision: 1.0.*
    helm:
      valuesObject:
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            hosts:
              - grafana.integration

  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
