apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://hiro-microdatacenters-bv.github.io/monitoring-stack/helm-charts/
    chart: monitoring-stack
    targetRevision: 1.0.*
    helm:
      valuesObject:

        prometheus:
          server:
            remoteWrite: []
        influxdb:
          enabled: false
        
        kubernetes-event-exporter:
          receivers:
          - name: "dump"
            stdout:
              deDot: true
          - name: "loki"
            loki:
              streamLabels:
                stream: kube-events
              url: http://monitoring-stack-loki:3100/loki/api/v1/push

        grafana:
          adminPassword: donkeyhot
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            hosts:
              - grafana.integration
        kepler:
          enabled: true

  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
