# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: dkg-engine
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/glaciation-heu/gitops-deployments
#     path: integration/apps/security
#     targetRevision: HEAD
#   destination:
#     namespace: argo-cd
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     automated: 
#      prune: true 
#      selfHeal: true 
#     syncOptions:
#       - ServerSideApply=true
