apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - gatekeeper-policy-manager.yaml
  - gatekeeper.yaml
  - replicator.yaml
  - setup-ca-and-bundle.yaml
  - trust-manager.yaml
  - vault.yaml
  